services:
  rohtembak:
    image: jrei/systemd-debian:12
    container_name: rohtembak
    hostname: rohtembak
    privileged: true
    ports:
      - "8000:8000"
    tmpfs:
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    environment:
      container: docker
    restart: unless-stopped
    stop_grace_period: 30s
    command: /sbin/init
